//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReckoningCounterTest.CounterOrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity")]
    [System.SerializableAttribute()]
    public partial class StockOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesTransactionDirection BuySellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float OrderAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OrderPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesUnitType OrderUnitTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesOrderPriceType OrderWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortfoliosIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesTransactionDirection BuySell {
            get {
                return this.BuySellField;
            }
            set {
                if ((this.BuySellField.Equals(value) != true)) {
                    this.BuySellField = value;
                    this.RaisePropertyChanged("BuySell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelID {
            get {
                return this.ChannelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelIDField, value) != true)) {
                    this.ChannelIDField = value;
                    this.RaisePropertyChanged("ChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float OrderAmount {
            get {
                return this.OrderAmountField;
            }
            set {
                if ((this.OrderAmountField.Equals(value) != true)) {
                    this.OrderAmountField = value;
                    this.RaisePropertyChanged("OrderAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OrderPrice {
            get {
                return this.OrderPriceField;
            }
            set {
                if ((this.OrderPriceField.Equals(value) != true)) {
                    this.OrderPriceField = value;
                    this.RaisePropertyChanged("OrderPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesUnitType OrderUnitType {
            get {
                return this.OrderUnitTypeField;
            }
            set {
                if ((this.OrderUnitTypeField.Equals(value) != true)) {
                    this.OrderUnitTypeField = value;
                    this.RaisePropertyChanged("OrderUnitType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesOrderPriceType OrderWay {
            get {
                return this.OrderWayField;
            }
            set {
                if ((this.OrderWayField.Equals(value) != true)) {
                    this.OrderWayField = value;
                    this.RaisePropertyChanged("OrderWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortfoliosId {
            get {
                return this.PortfoliosIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfoliosIdField, value) != true)) {
                    this.PortfoliosIdField = value;
                    this.RaisePropertyChanged("PortfoliosId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderId {
            get {
                return this.TraderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderIdField, value) != true)) {
                    this.TraderIdField = value;
                    this.RaisePropertyChanged("TraderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderPassword {
            get {
                return this.TraderPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderPasswordField, value) != true)) {
                    this.TraderPasswordField = value;
                    this.RaisePropertyChanged("TraderPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Types.TransactionDirection", Namespace="http://schemas.datacontract.org/2004/07/CommonObject")]
    public enum TypesTransactionDirection : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Buying = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Selling = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Types.UnitType", Namespace="http://schemas.datacontract.org/2004/07/CommonObject")]
    public enum TypesUnitType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thigh = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hand = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sheet = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Point = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ton = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gram = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IndexPoints = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Types.OrderPriceType", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity.Contants")]
    public enum TypesOrderPriceType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OPTLimited = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OPTMarketPrice = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderResponse", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity")]
    [System.SerializableAttribute()]
    public partial class OrderResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDatetime {
            get {
                return this.OrderDatetimeField;
            }
            set {
                if ((this.OrderDatetimeField.Equals(value) != true)) {
                    this.OrderDatetimeField = value;
                    this.RaisePropertyChanged("OrderDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderMessage {
            get {
                return this.OrderMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderMessageField, value) != true)) {
                    this.OrderMessageField = value;
                    this.RaisePropertyChanged("OrderMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MercantileFuturesOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity")]
    [System.SerializableAttribute()]
    public partial class MercantileFuturesOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesTransactionDirection BuySellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesFutureOpenCloseType OpenOffsetFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float OrderAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OrderPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesUnitType OrderUnitTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesOrderPriceType OrderWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortfoliosIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesTransactionDirection BuySell {
            get {
                return this.BuySellField;
            }
            set {
                if ((this.BuySellField.Equals(value) != true)) {
                    this.BuySellField = value;
                    this.RaisePropertyChanged("BuySell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelID {
            get {
                return this.ChannelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelIDField, value) != true)) {
                    this.ChannelIDField = value;
                    this.RaisePropertyChanged("ChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesFutureOpenCloseType OpenOffsetFlag {
            get {
                return this.OpenOffsetFlagField;
            }
            set {
                if ((this.OpenOffsetFlagField.Equals(value) != true)) {
                    this.OpenOffsetFlagField = value;
                    this.RaisePropertyChanged("OpenOffsetFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float OrderAmount {
            get {
                return this.OrderAmountField;
            }
            set {
                if ((this.OrderAmountField.Equals(value) != true)) {
                    this.OrderAmountField = value;
                    this.RaisePropertyChanged("OrderAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OrderPrice {
            get {
                return this.OrderPriceField;
            }
            set {
                if ((this.OrderPriceField.Equals(value) != true)) {
                    this.OrderPriceField = value;
                    this.RaisePropertyChanged("OrderPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesUnitType OrderUnitType {
            get {
                return this.OrderUnitTypeField;
            }
            set {
                if ((this.OrderUnitTypeField.Equals(value) != true)) {
                    this.OrderUnitTypeField = value;
                    this.RaisePropertyChanged("OrderUnitType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesOrderPriceType OrderWay {
            get {
                return this.OrderWayField;
            }
            set {
                if ((this.OrderWayField.Equals(value) != true)) {
                    this.OrderWayField = value;
                    this.RaisePropertyChanged("OrderWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortfoliosId {
            get {
                return this.PortfoliosIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfoliosIdField, value) != true)) {
                    this.PortfoliosIdField = value;
                    this.RaisePropertyChanged("PortfoliosId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderId {
            get {
                return this.TraderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderIdField, value) != true)) {
                    this.TraderIdField = value;
                    this.RaisePropertyChanged("TraderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderPassword {
            get {
                return this.TraderPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderPasswordField, value) != true)) {
                    this.TraderPasswordField = value;
                    this.RaisePropertyChanged("TraderPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Types.FutureOpenCloseType", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity.Contants")]
    public enum TypesFutureOpenCloseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OpenPosition = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClosePosition = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CloseTodayPosition = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockIndexFuturesOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity")]
    [System.SerializableAttribute()]
    public partial class StockIndexFuturesOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesTransactionDirection BuySellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesFutureOpenCloseType OpenCloseTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float OrderAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OrderPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesUnitType OrderUnitTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesOrderPriceType OrderWayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortfoliosIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraderPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesTransactionDirection BuySell {
            get {
                return this.BuySellField;
            }
            set {
                if ((this.BuySellField.Equals(value) != true)) {
                    this.BuySellField = value;
                    this.RaisePropertyChanged("BuySell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelID {
            get {
                return this.ChannelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelIDField, value) != true)) {
                    this.ChannelIDField = value;
                    this.RaisePropertyChanged("ChannelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesFutureOpenCloseType OpenCloseType {
            get {
                return this.OpenCloseTypeField;
            }
            set {
                if ((this.OpenCloseTypeField.Equals(value) != true)) {
                    this.OpenCloseTypeField = value;
                    this.RaisePropertyChanged("OpenCloseType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float OrderAmount {
            get {
                return this.OrderAmountField;
            }
            set {
                if ((this.OrderAmountField.Equals(value) != true)) {
                    this.OrderAmountField = value;
                    this.RaisePropertyChanged("OrderAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OrderPrice {
            get {
                return this.OrderPriceField;
            }
            set {
                if ((this.OrderPriceField.Equals(value) != true)) {
                    this.OrderPriceField = value;
                    this.RaisePropertyChanged("OrderPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesUnitType OrderUnitType {
            get {
                return this.OrderUnitTypeField;
            }
            set {
                if ((this.OrderUnitTypeField.Equals(value) != true)) {
                    this.OrderUnitTypeField = value;
                    this.RaisePropertyChanged("OrderUnitType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesOrderPriceType OrderWay {
            get {
                return this.OrderWayField;
            }
            set {
                if ((this.OrderWayField.Equals(value) != true)) {
                    this.OrderWayField = value;
                    this.RaisePropertyChanged("OrderWay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortfoliosId {
            get {
                return this.PortfoliosIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PortfoliosIdField, value) != true)) {
                    this.PortfoliosIdField = value;
                    this.RaisePropertyChanged("PortfoliosId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderId {
            get {
                return this.TraderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderIdField, value) != true)) {
                    this.TraderIdField = value;
                    this.RaisePropertyChanged("TraderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraderPassword {
            get {
                return this.TraderPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.TraderPasswordField, value) != true)) {
                    this.TraderPasswordField = value;
                    this.RaisePropertyChanged("TraderPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockDealOrderPushBack", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity")]
    [System.SerializableAttribute()]
    public partial class StockDealOrderPushBack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DealDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DealPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesOrderStateType OrderStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealAmount {
            get {
                return this.DealAmountField;
            }
            set {
                if ((this.DealAmountField.Equals(value) != true)) {
                    this.DealAmountField = value;
                    this.RaisePropertyChanged("DealAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DealDatetime {
            get {
                return this.DealDatetimeField;
            }
            set {
                if ((this.DealDatetimeField.Equals(value) != true)) {
                    this.DealDatetimeField = value;
                    this.RaisePropertyChanged("DealDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealId {
            get {
                return this.DealIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DealIdField, value) != true)) {
                    this.DealIdField = value;
                    this.RaisePropertyChanged("DealId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DealPrice {
            get {
                return this.DealPriceField;
            }
            set {
                if ((this.DealPriceField.Equals(value) != true)) {
                    this.DealPriceField = value;
                    this.RaisePropertyChanged("DealPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesOrderStateType OrderState {
            get {
                return this.OrderStateField;
            }
            set {
                if ((this.OrderStateField.Equals(value) != true)) {
                    this.OrderStateField = value;
                    this.RaisePropertyChanged("OrderState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Types.OrderStateType", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity.Contants")]
    public enum TypesOrderStateType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSUnRequired = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSRequiredSoon = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSRequiredRemoveSoon = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSIsRequired = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSCanceled = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSRemoved = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSPartRemoved = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSPartDealed = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSDealed = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOSPartDealRemoveSoon = 11,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FutureDealOrderPushBack", Namespace="http://schemas.datacontract.org/2004/07/ReckoningCounter.Entity")]
    [System.SerializableAttribute()]
    public partial class FutureDealOrderPushBack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DealAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DealDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DealIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DealPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReckoningCounterTest.CounterOrderService.TypesOrderStateType OrderStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DealAmount {
            get {
                return this.DealAmountField;
            }
            set {
                if ((this.DealAmountField.Equals(value) != true)) {
                    this.DealAmountField = value;
                    this.RaisePropertyChanged("DealAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DealDatetime {
            get {
                return this.DealDatetimeField;
            }
            set {
                if ((this.DealDatetimeField.Equals(value) != true)) {
                    this.DealDatetimeField = value;
                    this.RaisePropertyChanged("DealDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealId {
            get {
                return this.DealIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DealIdField, value) != true)) {
                    this.DealIdField = value;
                    this.RaisePropertyChanged("DealId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DealPrice {
            get {
                return this.DealPriceField;
            }
            set {
                if ((this.DealPriceField.Equals(value) != true)) {
                    this.DealPriceField = value;
                    this.RaisePropertyChanged("DealPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReckoningCounterTest.CounterOrderService.TypesOrderStateType OrderState {
            get {
                return this.OrderStateField;
            }
            set {
                if ((this.OrderStateField.Equals(value) != true)) {
                    this.OrderStateField = value;
                    this.RaisePropertyChanged("OrderState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CounterOrderService.IDoOrder")]
    public interface IDoOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoOrder/DoStockOrder", ReplyAction="http://tempuri.org/IDoOrder/DoStockOrderResponse")]
        ReckoningCounterTest.CounterOrderService.OrderResponse DoStockOrder(ReckoningCounterTest.CounterOrderService.StockOrderRequest stockorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoOrder/DoMercantileFuturesOrder", ReplyAction="http://tempuri.org/IDoOrder/DoMercantileFuturesOrderResponse")]
        ReckoningCounterTest.CounterOrderService.OrderResponse DoMercantileFuturesOrder(ReckoningCounterTest.CounterOrderService.MercantileFuturesOrderRequest futuresorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoOrder/DoStockIndexFuturesOrder", ReplyAction="http://tempuri.org/IDoOrder/DoStockIndexFuturesOrderResponse")]
        ReckoningCounterTest.CounterOrderService.OrderResponse DoStockIndexFuturesOrder(ReckoningCounterTest.CounterOrderService.StockIndexFuturesOrderRequest futuresorder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoOrder/CancelStockOrder", ReplyAction="http://tempuri.org/IDoOrder/CancelStockOrderResponse")]
        bool CancelStockOrder(string OrderId, ref string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoOrder/CancelMercantileFuturesOrder", ReplyAction="http://tempuri.org/IDoOrder/CancelMercantileFuturesOrderResponse")]
        bool CancelMercantileFuturesOrder(string OrderId, ref string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDoOrder/CancelStockIndexFuturesOrder", ReplyAction="http://tempuri.org/IDoOrder/CancelStockIndexFuturesOrderResponse")]
        bool CancelStockIndexFuturesOrder(string OrderId, ref string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoOrderChannel : ReckoningCounterTest.CounterOrderService.IDoOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoOrderClient : System.ServiceModel.ClientBase<ReckoningCounterTest.CounterOrderService.IDoOrder>, ReckoningCounterTest.CounterOrderService.IDoOrder {
        
        public DoOrderClient() {
        }
        
        public DoOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ReckoningCounterTest.CounterOrderService.OrderResponse DoStockOrder(ReckoningCounterTest.CounterOrderService.StockOrderRequest stockorder) {
            return base.Channel.DoStockOrder(stockorder);
        }
        
        public ReckoningCounterTest.CounterOrderService.OrderResponse DoMercantileFuturesOrder(ReckoningCounterTest.CounterOrderService.MercantileFuturesOrderRequest futuresorder) {
            return base.Channel.DoMercantileFuturesOrder(futuresorder);
        }
        
        public ReckoningCounterTest.CounterOrderService.OrderResponse DoStockIndexFuturesOrder(ReckoningCounterTest.CounterOrderService.StockIndexFuturesOrderRequest futuresorder) {
            return base.Channel.DoStockIndexFuturesOrder(futuresorder);
        }
        
        public bool CancelStockOrder(string OrderId, ref string message) {
            return base.Channel.CancelStockOrder(OrderId, ref message);
        }
        
        public bool CancelMercantileFuturesOrder(string OrderId, ref string message) {
            return base.Channel.CancelMercantileFuturesOrder(OrderId, ref message);
        }
        
        public bool CancelStockIndexFuturesOrder(string OrderId, ref string message) {
            return base.Channel.CancelStockIndexFuturesOrder(OrderId, ref message);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CounterOrderService.IOrderDealRpt", CallbackContract=typeof(ReckoningCounterTest.CounterOrderService.IOrderDealRptCallback))]
    public interface IOrderDealRpt {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderDealRpt/RegisterChannel", ReplyAction="http://tempuri.org/IOrderDealRpt/RegisterChannelResponse")]
        bool RegisterChannel(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderDealRpt/UnRegisterChannel", ReplyAction="http://tempuri.org/IOrderDealRpt/UnRegisterChannelResponse")]
        bool UnRegisterChannel(string clientId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderDealRptCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderDealRpt/ProcessStockDealRpt", ReplyAction="http://tempuri.org/IOrderDealRpt/ProcessStockDealRptResponse")]
        void ProcessStockDealRpt(ReckoningCounterTest.CounterOrderService.StockDealOrderPushBack drsip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderDealRpt/ProcessMercantileDealRpt", ReplyAction="http://tempuri.org/IOrderDealRpt/ProcessMercantileDealRptResponse")]
        void ProcessMercantileDealRpt(ReckoningCounterTest.CounterOrderService.FutureDealOrderPushBack drmip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderDealRpt/ProcessStockIndexFuturesDealRpt", ReplyAction="http://tempuri.org/IOrderDealRpt/ProcessStockIndexFuturesDealRptResponse")]
        void ProcessStockIndexFuturesDealRpt(ReckoningCounterTest.CounterOrderService.FutureDealOrderPushBack drsifi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderDealRptChannel : ReckoningCounterTest.CounterOrderService.IOrderDealRpt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderDealRptClient : System.ServiceModel.DuplexClientBase<ReckoningCounterTest.CounterOrderService.IOrderDealRpt>, ReckoningCounterTest.CounterOrderService.IOrderDealRpt {
        
        public OrderDealRptClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public OrderDealRptClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public OrderDealRptClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDealRptClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDealRptClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool RegisterChannel(string clientId) {
            return base.Channel.RegisterChannel(clientId);
        }
        
        public bool UnRegisterChannel(string clientId) {
            return base.Channel.UnRegisterChannel(clientId);
        }
    }
}
