//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchCenter.DAL.HKTradingRulesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XH_MinVolumeOfBusiness", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class XH_MinVolumeOfBusiness : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BreedClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinVolumeOfBusinessIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TradeWayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VolumeOfBusinessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BreedClassID {
            get {
                return this.BreedClassIDField;
            }
            set {
                if ((this.BreedClassIDField.Equals(value) != true)) {
                    this.BreedClassIDField = value;
                    this.RaisePropertyChanged("BreedClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinVolumeOfBusinessID {
            get {
                return this.MinVolumeOfBusinessIDField;
            }
            set {
                if ((this.MinVolumeOfBusinessIDField.Equals(value) != true)) {
                    this.MinVolumeOfBusinessIDField = value;
                    this.RaisePropertyChanged("MinVolumeOfBusinessID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TradeWayID {
            get {
                return this.TradeWayIDField;
            }
            set {
                if ((this.TradeWayIDField.Equals(value) != true)) {
                    this.TradeWayIDField = value;
                    this.RaisePropertyChanged("TradeWayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UnitID {
            get {
                return this.UnitIDField;
            }
            set {
                if ((this.UnitIDField.Equals(value) != true)) {
                    this.UnitIDField = value;
                    this.RaisePropertyChanged("UnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VolumeOfBusiness {
            get {
                return this.VolumeOfBusinessField;
            }
            set {
                if ((this.VolumeOfBusinessField.Equals(value) != true)) {
                    this.VolumeOfBusinessField = value;
                    this.RaisePropertyChanged("VolumeOfBusiness");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XH_SpotPosition", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class XH_SpotPosition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BreedClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BreedClassID {
            get {
                return this.BreedClassIDField;
            }
            set {
                if ((this.BreedClassIDField.Equals(value) != true)) {
                    this.BreedClassIDField = value;
                    this.RaisePropertyChanged("BreedClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HK_Commodity", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(MatchCenter.DAL.HKTradingRulesService.OnstageHK_Commodity))]
    public partial class HK_Commodity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BreedClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HKCommodityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HKCommodityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ISSysDefaultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IsSellNullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MarketDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PerHandThighOrShareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockPinYinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> turnovervolumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BreedClassID {
            get {
                return this.BreedClassIDField;
            }
            set {
                if ((this.BreedClassIDField.Equals(value) != true)) {
                    this.BreedClassIDField = value;
                    this.RaisePropertyChanged("BreedClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HKCommodityCode {
            get {
                return this.HKCommodityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HKCommodityCodeField, value) != true)) {
                    this.HKCommodityCodeField = value;
                    this.RaisePropertyChanged("HKCommodityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HKCommodityName {
            get {
                return this.HKCommodityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HKCommodityNameField, value) != true)) {
                    this.HKCommodityNameField = value;
                    this.RaisePropertyChanged("HKCommodityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ISSysDefaultCode {
            get {
                return this.ISSysDefaultCodeField;
            }
            set {
                if ((this.ISSysDefaultCodeField.Equals(value) != true)) {
                    this.ISSysDefaultCodeField = value;
                    this.RaisePropertyChanged("ISSysDefaultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IsSellNull {
            get {
                return this.IsSellNullField;
            }
            set {
                if ((this.IsSellNullField.Equals(value) != true)) {
                    this.IsSellNullField = value;
                    this.RaisePropertyChanged("IsSellNull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MarketDate {
            get {
                return this.MarketDateField;
            }
            set {
                if ((this.MarketDateField.Equals(value) != true)) {
                    this.MarketDateField = value;
                    this.RaisePropertyChanged("MarketDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PerHandThighOrShare {
            get {
                return this.PerHandThighOrShareField;
            }
            set {
                if ((this.PerHandThighOrShareField.Equals(value) != true)) {
                    this.PerHandThighOrShareField = value;
                    this.RaisePropertyChanged("PerHandThighOrShare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StockPinYin {
            get {
                return this.StockPinYinField;
            }
            set {
                if ((object.ReferenceEquals(this.StockPinYinField, value) != true)) {
                    this.StockPinYinField = value;
                    this.RaisePropertyChanged("StockPinYin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> turnovervolume {
            get {
                return this.turnovervolumeField;
            }
            set {
                if ((this.turnovervolumeField.Equals(value) != true)) {
                    this.turnovervolumeField = value;
                    this.RaisePropertyChanged("turnovervolume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OnstageHK_Commodity", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class OnstageHK_Commodity : MatchCenter.DAL.HKTradingRulesService.HK_Commodity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NindcdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nindcd {
            get {
                return this.NindcdField;
            }
            set {
                if ((object.ReferenceEquals(this.NindcdField, value) != true)) {
                    this.NindcdField = value;
                    this.RaisePropertyChanged("Nindcd");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HK_SpotCosts", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class HK_SpotCosts : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BreedClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CommisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CommisionStartingpointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CurrencyTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> MonitoringFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PoundageValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StampDutyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> StampDutyStartingpointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StampDutyTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SystemTollField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TransferTollField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BreedClassID {
            get {
                return this.BreedClassIDField;
            }
            set {
                if ((this.BreedClassIDField.Equals(value) != true)) {
                    this.BreedClassIDField = value;
                    this.RaisePropertyChanged("BreedClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Commision {
            get {
                return this.CommisionField;
            }
            set {
                if ((this.CommisionField.Equals(value) != true)) {
                    this.CommisionField = value;
                    this.RaisePropertyChanged("Commision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CommisionStartingpoint {
            get {
                return this.CommisionStartingpointField;
            }
            set {
                if ((this.CommisionStartingpointField.Equals(value) != true)) {
                    this.CommisionStartingpointField = value;
                    this.RaisePropertyChanged("CommisionStartingpoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CurrencyTypeID {
            get {
                return this.CurrencyTypeIDField;
            }
            set {
                if ((this.CurrencyTypeIDField.Equals(value) != true)) {
                    this.CurrencyTypeIDField = value;
                    this.RaisePropertyChanged("CurrencyTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> MonitoringFee {
            get {
                return this.MonitoringFeeField;
            }
            set {
                if ((this.MonitoringFeeField.Equals(value) != true)) {
                    this.MonitoringFeeField = value;
                    this.RaisePropertyChanged("MonitoringFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> PoundageValue {
            get {
                return this.PoundageValueField;
            }
            set {
                if ((this.PoundageValueField.Equals(value) != true)) {
                    this.PoundageValueField = value;
                    this.RaisePropertyChanged("PoundageValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StampDuty {
            get {
                return this.StampDutyField;
            }
            set {
                if ((this.StampDutyField.Equals(value) != true)) {
                    this.StampDutyField = value;
                    this.RaisePropertyChanged("StampDuty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StampDutyStartingpoint {
            get {
                return this.StampDutyStartingpointField;
            }
            set {
                if ((this.StampDutyStartingpointField.Equals(value) != true)) {
                    this.StampDutyStartingpointField = value;
                    this.RaisePropertyChanged("StampDutyStartingpoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StampDutyTypeID {
            get {
                return this.StampDutyTypeIDField;
            }
            set {
                if ((this.StampDutyTypeIDField.Equals(value) != true)) {
                    this.StampDutyTypeIDField = value;
                    this.RaisePropertyChanged("StampDutyTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SystemToll {
            get {
                return this.SystemTollField;
            }
            set {
                if ((this.SystemTollField.Equals(value) != true)) {
                    this.SystemTollField = value;
                    this.RaisePropertyChanged("SystemToll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TransferToll {
            get {
                return this.TransferTollField;
            }
            set {
                if ((this.TransferTollField.Equals(value) != true)) {
                    this.TransferTollField = value;
                    this.RaisePropertyChanged("TransferToll");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HK_SpotTradeRules", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class HK_SpotTradeRules : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BreedClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FundDeliveryInstitutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MarketUnitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxLeaveQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StockDeliveryInstitutionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BreedClassID {
            get {
                return this.BreedClassIDField;
            }
            set {
                if ((this.BreedClassIDField.Equals(value) != true)) {
                    this.BreedClassIDField = value;
                    this.RaisePropertyChanged("BreedClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FundDeliveryInstitution {
            get {
                return this.FundDeliveryInstitutionField;
            }
            set {
                if ((this.FundDeliveryInstitutionField.Equals(value) != true)) {
                    this.FundDeliveryInstitutionField = value;
                    this.RaisePropertyChanged("FundDeliveryInstitution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MarketUnitID {
            get {
                return this.MarketUnitIDField;
            }
            set {
                if ((this.MarketUnitIDField.Equals(value) != true)) {
                    this.MarketUnitIDField = value;
                    this.RaisePropertyChanged("MarketUnitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxLeaveQuantity {
            get {
                return this.MaxLeaveQuantityField;
            }
            set {
                if ((this.MaxLeaveQuantityField.Equals(value) != true)) {
                    this.MaxLeaveQuantityField = value;
                    this.RaisePropertyChanged("MaxLeaveQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PriceUnit {
            get {
                return this.PriceUnitField;
            }
            set {
                if ((this.PriceUnitField.Equals(value) != true)) {
                    this.PriceUnitField = value;
                    this.RaisePropertyChanged("PriceUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StockDeliveryInstitution {
            get {
                return this.StockDeliveryInstitutionField;
            }
            set {
                if ((this.StockDeliveryInstitutionField.Equals(value) != true)) {
                    this.StockDeliveryInstitutionField = value;
                    this.RaisePropertyChanged("StockDeliveryInstitution");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HK_MinPriceFieldRange", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class HK_MinPriceFieldRange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FieldRangeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LowerLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UpperLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FieldRangeID {
            get {
                return this.FieldRangeIDField;
            }
            set {
                if ((this.FieldRangeIDField.Equals(value) != true)) {
                    this.FieldRangeIDField = value;
                    this.RaisePropertyChanged("FieldRangeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LowerLimit {
            get {
                return this.LowerLimitField;
            }
            set {
                if ((this.LowerLimitField.Equals(value) != true)) {
                    this.LowerLimitField = value;
                    this.RaisePropertyChanged("LowerLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UpperLimit {
            get {
                return this.UpperLimitField;
            }
            set {
                if ((this.UpperLimitField.Equals(value) != true)) {
                    this.UpperLimitField = value;
                    this.RaisePropertyChanged("UpperLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HKProfessionInfo", Namespace="http://schemas.datacontract.org/2004/07/ManagementCenter.Model")]
    [System.SerializableAttribute()]
    public partial class HKProfessionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnNindnmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NindcdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NindnmeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnNindnme {
            get {
                return this.EnNindnmeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnNindnmeField, value) != true)) {
                    this.EnNindnmeField = value;
                    this.RaisePropertyChanged("EnNindnme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nindcd {
            get {
                return this.NindcdField;
            }
            set {
                if ((object.ReferenceEquals(this.NindcdField, value) != true)) {
                    this.NindcdField = value;
                    this.RaisePropertyChanged("Nindcd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nindnme {
            get {
                return this.NindnmeField;
            }
            set {
                if ((object.ReferenceEquals(this.NindnmeField, value) != true)) {
                    this.NindnmeField = value;
                    this.RaisePropertyChanged("Nindnme");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HKTradingRulesService.IHKTradeRules")]
    public interface IHKTradeRules {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetAllMinVolumeOfBusiness", ReplyAction="http://tempuri.org/IHKTradeRules/GetAllMinVolumeOfBusinessResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.XH_MinVolumeOfBusiness> GetAllMinVolumeOfBusiness();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetMinVolumeOfBusinessByBreedClassID", ReplyAction="http://tempuri.org/IHKTradeRules/GetMinVolumeOfBusinessByBreedClassIDResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.XH_MinVolumeOfBusiness> GetMinVolumeOfBusinessByBreedClassID(int breedClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetAllSpotPosition", ReplyAction="http://tempuri.org/IHKTradeRules/GetAllSpotPositionResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.XH_SpotPosition> GetAllSpotPosition();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetSpotPositionByBreedClassID", ReplyAction="http://tempuri.org/IHKTradeRules/GetSpotPositionByBreedClassIDResponse")]
        MatchCenter.DAL.HKTradingRulesService.XH_SpotPosition GetSpotPositionByBreedClassID(int breedClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetAllHKCommodity", ReplyAction="http://tempuri.org/IHKTradeRules/GetAllHKCommodityResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_Commodity> GetAllHKCommodity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetHKCommodityByHKCommodityCode", ReplyAction="http://tempuri.org/IHKTradeRules/GetHKCommodityByHKCommodityCodeResponse")]
        MatchCenter.DAL.HKTradingRulesService.HK_Commodity GetHKCommodityByHKCommodityCode(string hkcommodityCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetHKCommodityByBreedClassID", ReplyAction="http://tempuri.org/IHKTradeRules/GetHKCommodityByBreedClassIDResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_Commodity> GetHKCommodityByBreedClassID(int breedClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetNewHKCommodity", ReplyAction="http://tempuri.org/IHKTradeRules/GetNewHKCommodityResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_Commodity> GetNewHKCommodity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetAllHKSpotCosts", ReplyAction="http://tempuri.org/IHKTradeRules/GetAllHKSpotCostsResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_SpotCosts> GetAllHKSpotCosts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetHKSpotCostsByBreedClassID", ReplyAction="http://tempuri.org/IHKTradeRules/GetHKSpotCostsByBreedClassIDResponse")]
        MatchCenter.DAL.HKTradingRulesService.HK_SpotCosts GetHKSpotCostsByBreedClassID(int breedClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetAllHKSpotTradeRules", ReplyAction="http://tempuri.org/IHKTradeRules/GetAllHKSpotTradeRulesResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_SpotTradeRules> GetAllHKSpotTradeRules();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetHKSpotTradeRulesByBreedClassID", ReplyAction="http://tempuri.org/IHKTradeRules/GetHKSpotTradeRulesByBreedClassIDResponse")]
        MatchCenter.DAL.HKTradingRulesService.HK_SpotTradeRules GetHKSpotTradeRulesByBreedClassID(int breedClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetAllHKMinPriceFieldRange", ReplyAction="http://tempuri.org/IHKTradeRules/GetAllHKMinPriceFieldRangeResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_MinPriceFieldRange> GetAllHKMinPriceFieldRange();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetHKCommodityListArray", ReplyAction="http://tempuri.org/IHKTradeRules/GetHKCommodityListArrayResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.OnstageHK_Commodity> GetHKCommodityListArray();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHKTradeRules/GetListHKProfessionInfoArray", ReplyAction="http://tempuri.org/IHKTradeRules/GetListHKProfessionInfoArrayResponse")]
        System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HKProfessionInfo> GetListHKProfessionInfoArray();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHKTradeRulesChannel : MatchCenter.DAL.HKTradingRulesService.IHKTradeRules, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HKTradeRulesClient : System.ServiceModel.ClientBase<MatchCenter.DAL.HKTradingRulesService.IHKTradeRules>, MatchCenter.DAL.HKTradingRulesService.IHKTradeRules {
        
        public HKTradeRulesClient() {
        }
        
        public HKTradeRulesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HKTradeRulesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HKTradeRulesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HKTradeRulesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.XH_MinVolumeOfBusiness> GetAllMinVolumeOfBusiness() {
            return base.Channel.GetAllMinVolumeOfBusiness();
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.XH_MinVolumeOfBusiness> GetMinVolumeOfBusinessByBreedClassID(int breedClassID) {
            return base.Channel.GetMinVolumeOfBusinessByBreedClassID(breedClassID);
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.XH_SpotPosition> GetAllSpotPosition() {
            return base.Channel.GetAllSpotPosition();
        }
        
        public MatchCenter.DAL.HKTradingRulesService.XH_SpotPosition GetSpotPositionByBreedClassID(int breedClassID) {
            return base.Channel.GetSpotPositionByBreedClassID(breedClassID);
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_Commodity> GetAllHKCommodity() {
            return base.Channel.GetAllHKCommodity();
        }
        
        public MatchCenter.DAL.HKTradingRulesService.HK_Commodity GetHKCommodityByHKCommodityCode(string hkcommodityCode) {
            return base.Channel.GetHKCommodityByHKCommodityCode(hkcommodityCode);
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_Commodity> GetHKCommodityByBreedClassID(int breedClassID) {
            return base.Channel.GetHKCommodityByBreedClassID(breedClassID);
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_Commodity> GetNewHKCommodity() {
            return base.Channel.GetNewHKCommodity();
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_SpotCosts> GetAllHKSpotCosts() {
            return base.Channel.GetAllHKSpotCosts();
        }
        
        public MatchCenter.DAL.HKTradingRulesService.HK_SpotCosts GetHKSpotCostsByBreedClassID(int breedClassID) {
            return base.Channel.GetHKSpotCostsByBreedClassID(breedClassID);
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_SpotTradeRules> GetAllHKSpotTradeRules() {
            return base.Channel.GetAllHKSpotTradeRules();
        }
        
        public MatchCenter.DAL.HKTradingRulesService.HK_SpotTradeRules GetHKSpotTradeRulesByBreedClassID(int breedClassID) {
            return base.Channel.GetHKSpotTradeRulesByBreedClassID(breedClassID);
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HK_MinPriceFieldRange> GetAllHKMinPriceFieldRange() {
            return base.Channel.GetAllHKMinPriceFieldRange();
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.OnstageHK_Commodity> GetHKCommodityListArray() {
            return base.Channel.GetHKCommodityListArray();
        }
        
        public System.Collections.Generic.List<MatchCenter.DAL.HKTradingRulesService.HKProfessionInfo> GetListHKProfessionInfoArray() {
            return base.Channel.GetListHKProfessionInfoArray();
        }
    }
}
